version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:11.3.2021.22.16.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
