version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:13.3.2021.23.40.36"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
