version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:14.3.2021.15.55.25"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
