version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:12.3.2021.0.7.17"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
